import { ROUTES } from "../router/RouteConfig";

export const data = {};

export const BREADCRUMB_DATA = {
  CONDIDATES_APPPLIED: [ROUTES.HOME, ROUTES.CANDIDATES.childrens.APPLIED],
  CONDIDATES_CONTACTED: [ROUTES.HOME, ROUTES.CANDIDATES.childrens.CONTACTED],
  CONDIDATES_SHORTLISTED: [
    ROUTES.HOME,
    ROUTES.CANDIDATES.childrens.SHORTLISTED,
  ],
  CONDIDATES_INTERVIEWED: [
    ROUTES.HOME,
    ROUTES.CANDIDATES.childrens.INTERVIEWED,
  ],
  CONDIDATES_HIRED: [ROUTES.HOME, ROUTES.CANDIDATES.childrens.HIRED],
  CONDIDATES_REJECTED: [ROUTES.HOME, ROUTES.CANDIDATES.childrens.REJECTED],
  ADD_CADIDATE: [ROUTES.HOME, ROUTES.ADD_CANDIDATE],
};
